### ISSUE TITLE
Historic bots

### ISSUE THREAD

**Issue by vielmetti** [abdelhai/awesome-bots#3]
Don't know how you want to organize it, but there are some historic bots that deserve mention that current bots are descended from. At minimum I'd have ELIZA and PARRY and their early 1970s conversation. Here's a link

http://parrynoid.org/

for PARRY and the attempts to reanimate him.

**Comment by abdelhai** [comment]
@vielmetti Thanks! Makes sense.
I didn't add these since I have to read more about bot history in general to add the most interesting ones. Definitely coming soon.

**Comment by vielmetti** [comment]
Thanks @abdelhai ! I have been reading a bunch of history. For ELIZA I'd link to http://elizagen.org which has a whole lot of code. 

Hm, I might have enough to try a pull request with these two....
